cloud:
  version: 6
  product: SUSE OpenStack Cloud

admin_node:
  os:
    name: SUSE Linux Enterprise Server 12
    version: 12
    patchlevel: 0

  ip: localhost
  ssh:
    user: root
    password: linux
    port: 22

  api:
    user: crowbar
    password: crowbar
    port: 3000
    ssl: false

control_node:
  ssh:
    user: root
    password:
    port: 22

timeout:
  ssh: 5
  http: 5

